package com.aicostops.gateway.provider;

public enum ProviderSafetyReason {
    BUDGET_NO_MATCH_PRE_PROVIDER,
    BUDGET_INSUFFICIENT_PRE_PROVIDER,
    BUDGET_BOUND_UNSAFE_PRE_PROVIDER,
    CLIENT_CANCEL_BEFORE_DISPATCH,
    LOCAL_PRE_NETWORK_FAILURE,
    DNS_PRE_CONNECT,
    CONNECT_REFUSED_PRE_WRITE,
    CONNECT_TIMEOUT_PRE_WRITE,
    TLS_HANDSHAKE_PRE_HTTP_WRITE,
    HTTP_RESPONSE_RECEIVED,
    HEADER_TIMEOUT_WRITE_POSSIBLE,
    READ_TIMEOUT,
    STREAM_TIMEOUT,
    CONNECTION_RESET_WRITE_POSSIBLE,
    MALFORMED_PROVIDER_RESPONSE,
    CLIENT_CANCEL_AFTER_DISPATCH,
    UNKNOWN_POST_DISPATCH
}
