services:
  mysql:
    ports:
      - "${MYSQL_PORT}:3306"

  redis:
    ports:
      - "${REDIS_PORT}:6379"

  minio:
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
