package com.aicostops;

import static org.assertj.core.api.Assertions.assertThat;

import com.aicostops.testsupport.M2DatabaseCleaner;
import com.aicostops.testsupport.MySqlContainerSupport;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Reproducible MySQL EXPLAIN evidence for the M8 query/index review.
 *
 * <p>The fixture is deliberately representative rather than synthetic query
 * mocks: the plans are generated by MySQL after the real Flyway schema has been
 * applied, with tenant-scoped import, charge, duplicate-review and budget rows.
 */
@SpringBootTest
@Tag("integration")
class M8SchemaQueryExplainIntegrationTest extends MySqlContainerSupport {

    private static final String PERIOD_START = "2026-08-01 00:00:00.000000";
    private static final String PERIOD_END = "2026-09-01 00:00:00.000000";

    @Autowired
    private JdbcTemplate jdbc;

    private long organizationId;
    private long billingPeriodId;

    @BeforeEach
    void setUp() {
        M2DatabaseCleaner.clean(jdbc);
        organizationId = insertOrganization();
        var userId = insertUser();
        var memberId = insertMember(userId);
        var providerAccountId = insertProviderAccount();
        var evidenceId = insertEvidence(memberId);
        var batchId = insertBatch(evidenceId, providerAccountId, memberId);
        var attemptId = insertAttempt(batchId);
        jdbc.update("UPDATE import_batch SET status='CONFIRMED', confirmed_attempt_id=? WHERE id=?",
                attemptId, batchId);
        insertChargeLineage(attemptId, 240);

        jdbc.update("""
                INSERT INTO billing_period(
                    org_id,period_start,period_end,status,close_generation,version,created_at,updated_at)
                VALUES (?,?,?,'OPEN',0,0,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """, organizationId, PERIOD_START, PERIOD_END);
        billingPeriodId = jdbc.queryForObject(
                "SELECT id FROM billing_period WHERE org_id=? ORDER BY id DESC LIMIT 1", Long.class,
                organizationId);
        // A period can accumulate many scoped budgets over time. Use a larger
        // representative table here so a useful index must compete with a
        // full scan, rather than letting a 240-row toy table decide the plan.
        insertBudgets(10_000);
    }

    @AfterEach
    void tearDown() {
        M2DatabaseCleaner.clean(jdbc);
    }

    @Test
    void printsMySqlPlansForM8CoreWorkloads() {
        var mysqlVersion = jdbc.queryForObject("SELECT VERSION()", String.class);
        assertThat(mysqlVersion).isNotBlank();
        System.out.println("M8_EXPLAIN|mysql_version|" + mysqlVersion);

        printBudgetIndexEvidence("final");
        explainBudgetRepresentativeQueries("final");
        assertThat(hasBudgetIndex("idx_budget_org_period")).isFalse();

        explain("duplicate_review_page", """
                SELECT dc.id,dc.org_id,dc.charge_fact_id,dc.matched_charge_id,
                       dc.candidate_type,dc.status,dc.created_at
                FROM duplicate_candidate dc
                WHERE dc.org_id=? AND dc.status='OPEN' AND dc.candidate_type='EXACT'
                ORDER BY dc.created_at DESC,dc.id DESC
                LIMIT 50 OFFSET 0
                """, organizationId);

        explain("duplicate_review_by_charge", """
                SELECT dc.id,dc.charge_fact_id,dc.matched_charge_id,dc.status
                FROM duplicate_candidate dc
                WHERE dc.org_id=? AND dc.status='OPEN'
                  AND (dc.charge_fact_id=? OR dc.matched_charge_id=?)
                ORDER BY dc.id
                FOR UPDATE
                """, organizationId, 1L, 1L);

        explain("budget_lookup_by_period_without_m8_order_index", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency,
                       b.total_amount,b.actual_amount,b.committed_amount,b.status,b.version,
                       b.created_at,b.updated_at
                FROM budget b IGNORE INDEX (idx_budget_org_period_created_id)
                WHERE b.org_id=? AND b.billing_period_id=?
                ORDER BY b.created_at DESC,b.id DESC
                LIMIT 50 OFFSET 0
                """, organizationId, billingPeriodId);

        explain("budget_lookup_by_period", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency,
                       b.total_amount,b.actual_amount,b.committed_amount,b.status,b.version,
                       b.created_at,b.updated_at
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                ORDER BY b.created_at DESC,b.id DESC
                LIMIT 50 OFFSET 0
                """, organizationId, billingPeriodId);

        explain("budget_lookup_by_scope", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency,
                       b.total_amount,b.actual_amount,b.committed_amount
                FROM budget b
                WHERE b.org_id=? AND b.scope_type='PROJECT' AND b.scope_id=?
                  AND b.currency='USD'
                """, organizationId, 42L);

        explain("workbench_provider_cost", """
                SELECT cf.provider_code AS providerCode,cf.currency AS currency,
                       SUM(cf.amount) AS totalAmount,COUNT(*) AS chargeCount
                FROM charge_fact cf
                JOIN raw_provider_record rpr ON rpr.id=cf.raw_record_id
                JOIN import_attempt ia ON ia.id=rpr.import_attempt_id
                JOIN import_batch ib ON ib.id=ia.import_batch_id AND ib.org_id=cf.org_id
                WHERE cf.org_id=?
                  AND ib.status='CONFIRMED'
                  AND ib.confirmed_attempt_id=ia.id
                  AND cf.review_status='CLEAN'
                  AND cf.period_start>=? AND cf.period_start<?
                GROUP BY cf.provider_code,cf.currency
                ORDER BY SUM(cf.amount) DESC,cf.provider_code ASC
                LIMIT 20
                """, organizationId, PERIOD_START, PERIOD_END);

        explain("workbench_unallocated_currency", """
                SELECT cf.currency AS currency,SUM(cf.amount) AS amount,COUNT(*) AS chargeCount
                FROM charge_fact cf
                LEFT JOIN allocation_decision ad
                  ON ad.id=cf.current_allocation_decision_id AND ad.org_id=cf.org_id
                JOIN raw_provider_record rpr ON rpr.id=cf.raw_record_id
                JOIN import_attempt ia ON ia.id=rpr.import_attempt_id
                JOIN import_batch ib ON ib.id=ia.import_batch_id AND ib.org_id=cf.org_id
                WHERE cf.org_id=? AND ib.status='CONFIRMED'
                  AND ib.confirmed_attempt_id=ia.id AND cf.review_status='CLEAN'
                  AND cf.period_start>=? AND cf.period_start<?
                  AND (cf.current_allocation_decision_id IS NULL OR ad.status<>'CONFIRMED')
                GROUP BY cf.currency
                ORDER BY SUM(cf.amount) DESC
                """, organizationId, PERIOD_START, PERIOD_END);

        explain("import_queue_claim", """
                SELECT ia.id,ia.import_batch_id,ia.status,ia.available_at,ia.lease_until
                FROM import_attempt ia
                WHERE ia.status='QUEUED' AND ia.available_at<=UTC_TIMESTAMP(6)
                ORDER BY ia.available_at,ia.id
                LIMIT 1
                FOR UPDATE SKIP LOCKED
                """);
    }

    private void explain(String label, String sql, Object... args) {
        List<Map<String, Object>> plan = jdbc.queryForList("EXPLAIN " + sql, args);
        assertThat(plan).as(label).isNotEmpty();
        System.out.println("M8_EXPLAIN|" + label + "|" + plan);
    }

    private void explainBudgetRepresentativeQueries(String label) {
        explain("budget_" + label + "_period_page", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency,
                       b.total_amount,b.actual_amount,b.committed_amount,b.status,b.version,
                       b.created_at,b.updated_at
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                ORDER BY b.created_at DESC,b.id DESC
                LIMIT 50 OFFSET 0
                """, organizationId, billingPeriodId);
        explain("budget_" + label + "_period_order_id", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                ORDER BY b.id
                LIMIT 50
                """, organizationId, billingPeriodId);
        explain("budget_" + label + "_period_count", """
                SELECT COUNT(*)
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                """, organizationId, billingPeriodId);
        explain("budget_" + label + "_identity", """
                SELECT b.id,b.org_id,b.billing_period_id,b.scope_type,b.scope_id,b.currency
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                  AND b.scope_type='PROJECT' AND b.scope_id=? AND b.currency='USD'
                """, organizationId, billingPeriodId, 42L);
        explain("budget_" + label + "_period_integrity", """
                SELECT b.id,b.actual_amount,b.committed_amount
                FROM budget b
                WHERE b.org_id=? AND b.billing_period_id=?
                  AND (b.actual_amount <> 0 OR b.committed_amount <> 0)
                ORDER BY b.id
                LIMIT 50
                """, organizationId, billingPeriodId);
    }

    private void printBudgetIndexEvidence(String label) {
        var indexes = jdbc.queryForList("SHOW INDEX FROM budget");
        var foreignKeys = jdbc.queryForList("""
                SELECT kcu.CONSTRAINT_NAME,kcu.COLUMN_NAME,kcu.ORDINAL_POSITION,
                       kcu.REFERENCED_TABLE_NAME,kcu.REFERENCED_COLUMN_NAME
                FROM information_schema.KEY_COLUMN_USAGE kcu
                WHERE kcu.CONSTRAINT_SCHEMA=DATABASE()
                  AND kcu.TABLE_NAME='budget'
                  AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
                ORDER BY kcu.CONSTRAINT_NAME,kcu.ORDINAL_POSITION
                """);
        var createTable = jdbc.queryForObject("SHOW CREATE TABLE budget", (rs, rowNum) -> rs.getString(1));
        System.out.println("M8_BUDGET_INDEXES|" + label + "|" + indexes);
        System.out.println("M8_BUDGET_FKS|" + label + "|" + foreignKeys);
        System.out.println("M8_BUDGET_CREATE|" + label + "|" + createTable);
    }

    private boolean hasBudgetIndex(String indexName) {
        return !jdbc.queryForList("SHOW INDEX FROM budget WHERE Key_name=?", indexName).isEmpty();
    }

    private long insertOrganization() {
        jdbc.update("""
                INSERT INTO organization(name,slug,status,settings_json,created_at,updated_at)
                VALUES ('M8 Explain','m8-explain','ACTIVE',JSON_OBJECT(),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """);
        return jdbc.queryForObject("SELECT id FROM organization WHERE slug='m8-explain'", Long.class);
    }

    private long insertUser() {
        jdbc.update("""
                INSERT INTO app_user(email_normalized,display_name,status,security_version,created_at,updated_at)
                VALUES ('m8-explain@example.com','M8 Explain','ACTIVE',7,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """);
        return jdbc.queryForObject("SELECT id FROM app_user WHERE email_normalized='m8-explain@example.com'",
                Long.class);
    }

    private long insertMember(long userId) {
        jdbc.update("""
                INSERT INTO organization_member(org_id,user_id,status,joined_at)
                VALUES (?,?,'ACTIVE',UTC_TIMESTAMP(6))
                """, organizationId, userId);
        return jdbc.queryForObject("SELECT id FROM organization_member WHERE org_id=? AND user_id=?",
                Long.class, organizationId, userId);
    }

    private long insertProviderAccount() {
        jdbc.update("""
                INSERT INTO provider_account(
                    org_id,provider_code,display_name,external_account_ref,status,metadata_json,created_at,updated_at)
                VALUES (?,'DEEPSEEK','M8 Explain',NULL,'ACTIVE',JSON_OBJECT(),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """, organizationId);
        return jdbc.queryForObject("SELECT id FROM provider_account WHERE org_id=?", Long.class, organizationId);
    }

    private long insertEvidence(long memberId) {
        jdbc.update("""
                INSERT INTO evidence(
                    org_id,sha256,object_key,original_filename,media_type,size_bytes,
                    uploaded_by_member_id,storage_status,storage_error_code,created_at,updated_at)
                VALUES (?,?,'m8-explain-object','m8-explain.zip','application/zip',1,?,'AVAILABLE',NULL,
                    UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """, organizationId, "e".repeat(64), memberId);
        return jdbc.queryForObject("SELECT id FROM evidence WHERE org_id=?", Long.class, organizationId);
    }

    private long insertBatch(long evidenceId, long providerAccountId, long memberId) {
        jdbc.update("""
                INSERT INTO import_batch(
                    org_id,evidence_id,provider_account_id,expected_provider_code,source_type,
                    parser_version,status,period_start,period_end,created_by_member_id,created_at,updated_at)
                VALUES (?,?,?,?,?,'m8-explain-parser','CONFIRMED',?,?,?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """, organizationId, evidenceId, providerAccountId, "DEEPSEEK", "FILE_EXPORT",
                PERIOD_START, PERIOD_END, memberId);
        return jdbc.queryForObject("SELECT id FROM import_batch WHERE evidence_id=?", Long.class, evidenceId);
    }

    private long insertAttempt(long batchId) {
        jdbc.update("""
                INSERT INTO import_attempt(
                    import_batch_id,attempt_no,status,trigger_type,predecessor_attempt_id,
                    available_at,lease_owner,lease_until,lease_version,parser_version,
                    detected_provider_code,schema_fingerprint,started_at,finished_at,error_code,error_summary,
                    records_seen,records_valid,warning_count,error_count,created_at)
                VALUES (?,1,'SUCCEEDED','INITIAL',NULL,UTC_TIMESTAMP(6),NULL,NULL,0,'m8-explain-parser',
                    'DEEPSEEK','m8-explain-fingerprint',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),NULL,NULL,
                    240,240,0,0,UTC_TIMESTAMP(6))
                """, batchId);
        return jdbc.queryForObject("SELECT id FROM import_attempt WHERE import_batch_id=?", Long.class, batchId);
    }

    private void insertChargeLineage(long attemptId, int count) {
        for (var index = 0; index < count; index++) {
            jdbc.update("""
                    INSERT INTO raw_provider_record(
                        import_attempt_id,record_index,record_locator,provider_record_key,
                        raw_payload,normalized_payload,usage_start,usage_end,normalize_status,created_at)
                    VALUES (?, ?, ?, NULL, JSON_OBJECT(), NULL, ?, ?, 'NORMALIZED', UTC_TIMESTAMP(6))
                    """, attemptId, index, "m8-explain:row=" + index, PERIOD_START, PERIOD_END);
            var rawId = jdbc.queryForObject("SELECT LAST_INSERT_ID()", Long.class);
            jdbc.update("""
                    INSERT INTO charge_fact(
                        org_id,raw_record_id,fact_index,provider_code,charge_category,amount,currency,
                        period_start,period_end,review_status,created_at)
                    VALUES (?, ?, 0, 'DEEPSEEK','USAGE','1.25000000','USD',?,?, 'CLEAN',UTC_TIMESTAMP(6))
                    """, organizationId, rawId, PERIOD_START, PERIOD_END);
        }
        var chargeIds = jdbc.queryForList(
                "SELECT id FROM charge_fact WHERE org_id=? ORDER BY id", Long.class, organizationId);
        for (var index = 0; index < 120; index++) {
            jdbc.update("""
                    INSERT INTO duplicate_candidate(
                        org_id,charge_fact_id,matched_charge_id,candidate_type,fingerprint,
                        algorithm_version,match_reason,status,created_at)
                    VALUES (?,?,?,'EXACT',?,'m8-explain-v1','same synthetic fingerprint','OPEN',
                        UTC_TIMESTAMP(6))
                    """, organizationId, chargeIds.get(index), chargeIds.get(index + 1),
                    String.format("%064d", index + 1));
        }
    }

    private void insertBudgets(int count) {
        var arguments = new java.util.ArrayList<Object[]>(count);
        for (var index = 0; index < count; index++) {
            arguments.add(new Object[] {organizationId, billingPeriodId, index + 1});
        }
        jdbc.batchUpdate("""
                INSERT INTO budget(
                    org_id,billing_period_id,scope_type,scope_id,currency,total_amount,
                    actual_amount,committed_amount,status,version,created_at,updated_at)
                VALUES (?,?,'PROJECT',?,'USD','1000.00000000','0.00000000','0.00000000',
                    'ACTIVE',0,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))
                """, arguments);
    }
}
