package com.aicostops.shared.web;

public enum ProblemCode {
    REQUEST_MALFORMED,
    VALIDATION_FAILED,
    FORBIDDEN,
    AUTH_INVALID_CREDENTIALS,
    AUTH_ACCESS_EXPIRED,
    AUTH_SESSION_EXPIRED,
    AUTH_REFRESH_REPLAY,
    ACCOUNT_DISABLED,
    AUTH_REFRESH_RACE,
    AUTH_RATE_LIMITED,
    REDIS_UNAVAILABLE_FOR_AUTH,
    STATE_CONFLICT,
    RESOURCE_NOT_FOUND,
    DEPENDENCY_TEMPORARILY_UNAVAILABLE
}
